export default {
  "0058b4c6": [() => import(/* webpackChunkName: "0058b4c6" */ "@generated/docusaurus-plugin-content-docs/default/p/docs-175.json"), "@generated/docusaurus-plugin-content-docs/default/p/docs-175.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/docs-175.json")],
  "01d53cc9": [() => import(/* webpackChunkName: "01d53cc9" */ "@site/docs/5. Guides/newbie-guide.md"), "@site/docs/5. Guides/newbie-guide.md", require.resolveWeak("@site/docs/5. Guides/newbie-guide.md")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1f391b9e": [() => import(/* webpackChunkName: "1f391b9e" */ "@theme/MDXPage"), "@theme/MDXPage", require.resolveWeak("@theme/MDXPage")],
  "393be207": [() => import(/* webpackChunkName: "393be207" */ "@site/src/pages/markdown-page.md"), "@site/src/pages/markdown-page.md", require.resolveWeak("@site/src/pages/markdown-page.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "a7456010": [() => import(/* webpackChunkName: "a7456010" */ "@generated/docusaurus-plugin-content-pages/default/__plugin.json"), "@generated/docusaurus-plugin-content-pages/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-pages/default/__plugin.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "b980d436": [() => import(/* webpackChunkName: "b980d436" */ "@site/docs/1.General/league-rules.md"), "@site/docs/1.General/league-rules.md", require.resolveWeak("@site/docs/1.General/league-rules.md")],
  "c2d7d3f6": [() => import(/* webpackChunkName: "c2d7d3f6" */ "@site/docs/2. 4S Rules/4s-ruleset.md"), "@site/docs/2. 4S Rules/4s-ruleset.md", require.resolveWeak("@site/docs/2. 4S Rules/4s-ruleset.md")],
  "c4f5d8e4": [() => import(/* webpackChunkName: "c4f5d8e4" */ "@site/src/pages/index.js"), "@site/src/pages/index.js", require.resolveWeak("@site/src/pages/index.js")],
  "c743ffbf": [() => import(/* webpackChunkName: "c743ffbf" */ "@site/docs/3. Ultiduo Rules/ultiduo-ruleset.md"), "@site/docs/3. Ultiduo Rules/ultiduo-ruleset.md", require.resolveWeak("@site/docs/3. Ultiduo Rules/ultiduo-ruleset.md")],
  "f75dbd2e": [() => import(/* webpackChunkName: "f75dbd2e" */ "@site/docs/4. Sacred Scouts Rules/sacred-scouts-ruleset.md"), "@site/docs/4. Sacred Scouts Rules/sacred-scouts-ruleset.md", require.resolveWeak("@site/docs/4. Sacred Scouts Rules/sacred-scouts-ruleset.md")],};
